server:
  port: 8089

spring:
  datasource:
    # 指定为内存数据库H2
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    #MySQL driver class name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema: classpath:table.sql
    data: classpath:data.sql
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 150000
      connection-timeout: 30000
      connection-test-query: SELECT 1

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.springframework.web: ERROR
    com.example.spring.boot.jwt.mapper: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    # 日志文件输出样式
    #file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{18} - %msg%n"
  # 日志文件配置项
  #file:
  #  max-size: 5MB
  #  max-history: 20
#logging.file: logs.log
